roots = [
  ## Definitions we always need:
  "^Main.main$",
  "^Postmap.Cli.*$",
  "^Paths_postmap.*",

  ## Temporary suspensions:
  "^Postmap.Codegen.Haskell.Common.caseSchemaName$",
  "^Postmap.Codegen.Haskell.Common.columnNameToFieldName$",
  "^Zamazingo.*",
]
type-class-roots = true
